openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /magic-api/employees:
    get:
      tags:
      - employee-entity-controller
      description: get-employee
      operationId: getCollectionResource-employee-get
      parameters:
      - name: page
        in: query
        description: Zero-based page index (0..N)
        required: false
        schema:
          type: integer
          default: 0
          minimum: 0
      - name: size
        in: query
        description: The size of the page to be returned
        required: false
        schema:
          type: integer
          default: 20
          minimum: 1
      - name: sort
        in: query
        description: "Sorting criteria in the format: property,(asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/PagedModelEntityModelEmployee"
            application/x-spring-data-compact+json:
              schema:
                $ref: "#/components/schemas/PagedModelEntityModelEmployee"
            text/uri-list:
              schema:
                type: string
    post:
      tags:
      - employee-entity-controller
      description: create-employee
      operationId: postCollectionResource-employee-post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeRequestBody"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/EntityModelEmployee"
  /magic-api/employees/{id}:
    get:
      tags:
      - employee-entity-controller
      description: get-employee
      operationId: getItemResource-employee-get
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/EntityModelEmployee"
        "404":
          description: Not Found
    put:
      tags:
      - employee-entity-controller
      description: update-employee
      operationId: putItemResource-employee-put
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeRequestBody"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/EntityModelEmployee"
        "201":
          description: Created
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/EntityModelEmployee"
        "204":
          description: No Content
    delete:
      tags:
      - employee-entity-controller
      description: delete-employee
      operationId: deleteItemResource-employee-delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
    patch:
      tags:
      - employee-entity-controller
      description: patch-employee
      operationId: patchItemResource-employee-patch
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeRequestBody"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/EntityModelEmployee"
        "204":
          description: No Content
  /magic-api/profile:
    get:
      tags:
      - profile-controller
      operationId: listAllFormsOfMetadata
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: "#/components/schemas/RepresentationModelObject"
  /magic-api/profile/employees:
    get:
      tags:
      - profile-controller
      operationId: descriptor
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
            application/alps+json:
              schema:
                type: string
            application/schema+json:
              schema:
                $ref: "#/components/schemas/JsonSchema"
components:
  schemas:
    AbstractJsonSchemaPropertyObject:
      type: object
      properties:
        title:
          type: string
        readOnly:
          type: boolean
    Item:
      type: object
      properties:
        type:
          type: string
        properties:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/AbstractJsonSchemaPropertyObject"
        requiredProperties:
          type: array
          items:
            type: string
    JsonSchema:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        properties:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/AbstractJsonSchemaPropertyObject"
        requiredProperties:
          type: array
          items:
            type: string
        definitions:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Item"
        type:
          type: string
        $schema:
          type: string
    RepresentationModelObject:
      type: object
      properties:
        _links:
          $ref: "#/components/schemas/Links"
    EntityModelEmployee:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        _links:
          $ref: "#/components/schemas/Links"
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
          format: int64
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
    PagedModelEntityModelEmployee:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            employees:
              type: array
              items:
                $ref: "#/components/schemas/EntityModelEmployee"
        _links:
          $ref: "#/components/schemas/Links"
        page:
          $ref: "#/components/schemas/PageMetadata"
    EmployeeRequestBody:
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
    Links:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/Link"
